apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: vpromq01
  labels:
    app: rabmq
spec:
  selector:
    matchlabels:
      app: rabmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabmq
    spec:
      containers:
        - name: ramq01
          image: rabbitmq
          ports:
            - name: rammq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"